version: 2.1

executors:
  minimal:
    docker:
      - image: cimg/base:stable
    resource_class: small
    working_directory: ~/project

commands:
  prepare_workspace:
    steps:
      - checkout
      - run:
          name: Prepare public directory
          command: |
            mkdir -p public
            cp -v index.html public/
            cp -v styles.css public/
            cp -v script.js public/
      - store_artifacts:
          path: public
          destination: site
      - persist_to_workspace:
          root: .
          paths:
            - public

  quick_link_check:
    steps:
      - run:
          name: Quick HTML link check (fail-safe)
          command: |
            # Very fast sanity check to avoid long installs/timeouts
            # If linkinator is available, use it; otherwise skip without failing.
            if command -v npx >/dev/null 2>&1; then
              npx --yes linkinator public --silent --recurse --timeout 10000 || true
            else
              echo "npx not found; skipping link check";
            fi
          no_output_timeout: 5m

jobs:
  build:
    executor: minimal
    steps:
      - prepare_workspace
      - quick_link_check

  deploy_gh_pages:
    executor: minimal
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            # Replace with your CircleCI added SSH key fingerprint if you plan to deploy
            # - "aa:bb:cc:dd:ee:ff:00:11:22:33:44:55:66:77:88:99"
            []
      - run:
          name: Deploy to gh-pages branch (optional)
          command: |
            set -eo pipefail
            if [ -z "${GITHUB_REPOSITORY:-}" ]; then
              echo "GITHUB_REPOSITORY not set (e.g. user/repo). Skipping deploy." && exit 0
            fi
            git config --global user.email "ci@circleci"
            git config --global user.name "CircleCI"
            rm -rf /tmp/gh-pages
            git clone --depth 1 "git@github.com:${GITHUB_REPOSITORY}.git" /tmp/gh-pages
            cd /tmp/gh-pages
            git checkout -B gh-pages
            rm -rf *
            cp -r ~/project/public/* ./
            git add -A
            if git diff --cached --quiet; then
              echo "No changes to deploy." && exit 0
            fi
            git commit -m "Deploy site from CircleCI ${CIRCLE_SHA1}" || true
            git push -u origin gh-pages
          no_output_timeout: 5m

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
  deploy:
    when: << pipeline.parameters.run_deploy >>
    jobs:
      - build
      - deploy_gh_pages:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - main

parameters:
  run_deploy:
    type: boolean
    default: false


